config/routes.rb
SocialThing::Application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resource :reset_password do
    put "update_password"
    get "new_pass"
  end
  resources :friend_circles

end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :name, :member_ids

  has_many(
    :memberships,
    class_name: "FriendCircleMembership",
    foreign_key: :circle_id,
    primary_key: :id
  )


  has_many :members, through: :memberships, source: :user

end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :user_id, :circle_id

  validates :user_id, :circle_id, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to(
    :circle,
    class_name: "FriendCircle",
    foreign_key: :circle_id,
    primary_key: :id
  )


end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :post_id, :url


end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :session_token, :password_digest,
                  :password, :password_reset_token
  attr_reader :password

  validates :email, uniqueness: true
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6}, allow_nil: true
  before_validation :ensure_session_token


  has_many(
    :memberships,
    class_name: "FriendCircleMembership",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many :circles, through: :memberships, :source => :circle

  def self.find_by_credentials(email, password)
    u = User.find_by_email(email)
    return u if u && u.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  def self.generate_password_reset_token
    SecureRandom::urlsafe_base64(16)
  end

  def password_reset_token!
    self.password_reset_token = self.class.generate_password_reset_token
    self.save!
    self.password_reset_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    @users = User.all
    render :new
  end

  def create
    @friend_circle = FriendCircle.new(params[:friend_circle])
    @friend_circle.member_ids = params[:friend_circle_membership][:friends]
    # @friend_circle.memberships.new(params[:friend_circle_membership].values)

    if @friend_circle.save
      flash[:notice] = "#{@friend_circle.name} circle created!"
      redirect_to friend_circles_url
    else
      flash[:errors] = @friend_circle.errors.full_messages
      redirect_to new_friend_circle_url
    end
  end

  def index
    @friend_circles = FriendCircle.all
    render :index
  end

  def show
    @friend_circle = FriendCircle.new(params[:id])
    render :show
  end

  # def update
  #
  # end

  # def destroy
  #
  # end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user.nil?
      flash[:errors] = ["No such user!"]
      redirect_to new_session_url
    else
      reset_token = @user.password_reset_token!
      msg = UserMailer.reset_email(@user)
      msg.deliver!
      flash[:notice] = "Password reset email"
      redirect_to new_session_url
    end
  end

  def new_pass
    @user = User.find(params[:user])
    if @user && @user.password_reset_token == params[:reset_token]
      render :new_pass
    else
      redirect_to new_user_url
    end
  end

  def update
    @user = User.find(params[:user][:id])
    @user.update_attributes(:password => params[:user][:password])
    if @user.save
      flash[:notice] = "Password successfully changed"
      @user.password_reset_token = nil
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_session_url
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      session[:session_token] = @user.reset_session_token!
      redirect_to user_url(@user)
    else
      flash[:errors] = ["You done messed up."]
      redirect_to new_session_url
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "You successfully created a User!!!!!"
      session[:session_token] = @user.session_token
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  # def update
#     @user = User.find(params[:id])
#
#   end

  # def destroy
#   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!self.current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/index.html.erb
<h1>All Friend Circles!</h1>

<% @friend_circles.each do |fc| %>
  <%= fc.name %>
<% end %>

app/views/friend_circles/new.html.erb
<h1>Make a New Friend Circle!</h1>

<form action="<%= friend_circles_url %>" method="post">

  <input type="hidden" name="form_authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="friend_circle_name">Name Of Circle</label>
  <input type="text" name="friend_circle[name]" id="friend_circle_name">

  <br>

  <% @users.each do |user| %>

    <input type="checkbox" name="friend_circle_membership[friends][]" id="<%= user.id %>" value="<%= user.id %>">
    <label for="friend_name"><%= user.email %></label>
    <br>

  <% end %>

    <input type="submit" value="Create Friend Circle">
  </form>


</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
</head>
<body>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/reset_passwords/new.html.erb
<h1>What's Your Email?</h1>

<h4>We will reset your password and send you an email!</h4>

<form action="<%= reset_password_url %>" method="post">

  <input type="hidden" name="form_authenticity_token"
  value="<%= form_authenticity_token %>">

  <p>
    <label for="email">Email Address</label>
    <input type="text" id="email" name="user[email]">
  </p>

  <input type="submit" value="Send Reset Email">
</form>

app/views/reset_passwords/new_pass.html.erb
<h1>Create a New Password!</h1>

<h6>(And try not to forget it this time...)</h6>

<form action="<%= reset_password_url %>" method="post">

  <input type="hidden" name="_method" value="PUT">

  <input type="hidden" name="form_authenticity_token"
  value="<%= form_authenticity_token %>">

  <p>
    <label for="password">New Password</label>
    <input type="password" id="password" name="user[password]">
  </p>

  <input type="hidden" name="user[id]" value="<%= @user.id %>">
  <input type="submit" value="Reset Password">
</form>

app/views/reset_passwords/show.html.erb
<%= "A password reset email has been sent" %>

app/views/users/index.html.erb
<% @users.each do |user|%>
<%= user.email %>
<br>
<% end %>

app/views/users/new.html.erb
<h1>New User Sign-up!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="form_authenticity_token"
  value="<%= form_authenticity_token %>">

  <p>
  <label for="email">Email Address</label>
  <input type="text" id="email" name="user[email]">
  </p>

  <p>
  <label for="password">User Password</label>
  <input type="password" id="password" name="user[password]">
  </p>

  <input type="submit" value="Create User">

</form>

app/views/users/show.html.erb
<%= @user.email %>